### PR TITLE
Update Components to match with most recent practices in Aptos Move

### PR DESCRIPTION
**Pull request by GideonBature**
Update Move.toml file to reflect good practice and also make changes to the smart contract file to compile when run with the `aptos move run` command.

### CODE REVIEW

**Comment by huisq** [comment]
you have no incorporated move v2 at all 
https://aptos.dev/en/build/smart-contracts/book/move-2
https://aptos.dev/en/build/smart-contracts/compiler_v2

**Comment by GideonBature** [comment]
Thank you 

> you have no incorporated move v2 at all https://aptos.dev/en/build/smart-contracts/book/move-2 https://aptos.dev/en/build/smart-contracts/compiler_v2

Thank you ser!, exactly what I needed.

**Comment by GideonBature** [comment]
@huisq Please do check and confirm. Thank you for the docs.

**Comment by huisq** [comment]
Thank you!

**Comment by GideonBature** [comment]
@huisq you are welcome! Thank you for the docs. I am looking forward to making more contributions.

**Pull request merged**
